name: flutter_beacon_example
description: Demonstrates how to use the flutter_beacon plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  permission_handler: ^11.3.1
  flutter_beacon:
    path: ../
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
